server:
  port: 8085

spring:
  application:
    name: HOTEL-BOOKING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: HotelBookings

        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
